Implement UnusedArgument cop
DmitryTsepelev/rubocop-graphql pull request #61
Opened 2021-12-23 21:23 UTC by aishek

First of all, I've implemented autocorrection, and I am not sure if it is better than just add errors to arguments.

And the second thing is the cop ignores the case when there is no `resolve` method at all.

What do you think?

2021-12-24 14:14 UTC, DmitryTsepelev requested changes
Good start! Please check out my comments below and let's make CI pass

2021-12-28 21:20 UTC, aishek commented
Thanks for the comments! I've applied them, and also made the code backward compatible.

I am not sure if the following method if reliable enough:

```ruby
def method_name(node)
  node.loc.keyword.end.resize(node.method_name.to_s.size + 1)
end
```

`Util.args_begin` won't work for me somehow.

2021-12-29 11:29 UTC, DmitryTsepelev commented on lib/rubocop/cop/graphql/unused_argument.rb
> +          return unless resolve_method_nodes.any?
well, that was a bad suggestion, specs failing because of it 🥲

2021-12-29 11:30 UTC, DmitryTsepelev commented
Specs are still failing (because of my stupid suggestion mostly) and we have a number of rubocop offences 🙂

2021-12-29 15:03 UTC, aishek commented
Ok, I fixed it all :crossed_fingers:

2021-12-30 13:46 UTC, DmitryTsepelev approved these changes
LGTM, thank you!

2021-12-30 13:46 UTC, merged

2022-01-03 11:34 UTC, jgrau commented
Was the `loads:` argument considered? I have this chunk of code in a mutation:

```
...
    argument :booking_id, String, loads: Types::BookingType

    def resolve(booking:)
      ...
    end
...
```

but that complains that it wants `booking_id` to be a keyword argument in the `resolve` method.

:)

2022-01-03 14:34 UTC, aishek commented
> Was the `loads:` argument considered?

No, it was not. I will fix it, thanks!

2022-01-03 15:04 UTC, aishek commented
I've created the fix https://github.com/DmitryTsepelev/rubocop-graphql/pull/65